apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  enabled: true
  kind: helm
  repo: https://charts.kubegems.io/kubegems
  installNamespace: kubegems
  values:
    global:
      kubegemsVersion: main
      storageClass: local-path # change me to use a different storage class
    ingress:
      hostname: dashboard.kubegems.io # change me to use a production hostname
