apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  enabled: true
  kind: helm
  installNamespace: kubegems
  values:
    global:
      storageClass: local-path # change me to use a production storage class
      kubegemsVersion: main
    gitea:
      persistence:
        storageClass: local-path # change me to use a production storage class
    ingress:
      hostname: "*" # change me to use a production hostname
