apiVersion: v1
kind: Namespace
metadata:
  name: kubegems
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: mysql
  namespace: kubegems
spec:
  enabled: true
  kind: helm
  installNamespace: kubegems
  repo: https://charts.bitnami.com/bitnami
  version: 8.9.0
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  enabled: true
  kind: helm
  installNamespace: kubegems
  values:
    mysql:
      enabled: false
    externalDatabase:
      enabled: true
