apiVersion: v1
kind: Namespace
metadata:
  name: kubegems
---
apiVersion: plugins.kubegems.io/v1beta1
kind: Plugin
metadata:
  name: kubegems
  namespace: kubegems
spec:
  enabled: true
  kind: helm
  installNamespace: kubegems
  values:
    global:
      storageClass: local-path # change me to use a production storage class
      imageRegistry: docker.io
      kubegemsVersion: main
