# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
      - "release-*"
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '*.md'

env:
  IMAGE_NAME: ${{ github.repository }}
  GONOPROXY: kubegems.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/.cache/helm
            bin/plugins
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum','deploy/plugins') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Build binary
      - name: Build binaries
        run: make build GIT_VERSION=${GITHUB_REF_NAME}

      # Build images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Log into registry ${{ env.SECONDARY_REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.0.0
        with:
          registry: ${{ secrets.SECONDARY_REGISTRY }}
          username: ${{ secrets.SECONDARY_REGISTRY_USERNAME }}
          password: ${{ secrets.SECONDARY_REGISTRY_PASSWORD }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3.6.2
        with:
          images: ${{ secrets.REGISTRY }}/${{ env.IMAGE_NAME }},${{ secrets.SECONDARY_REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
